/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_Bitmap */

#ifndef _Included_android_graphics_Bitmap
#define _Included_android_graphics_Bitmap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_Bitmap
 * Method:    native_create_snapshot
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Bitmap_native_1create_1snapshot
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Bitmap
 * Method:    native_create_texture
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Bitmap_native_1create_1texture
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     android_graphics_Bitmap
 * Method:    native_get_width
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Bitmap_native_1get_1width
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Bitmap
 * Method:    native_get_height
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Bitmap_native_1get_1height
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Bitmap
 * Method:    native_erase_color
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Bitmap_native_1erase_1color
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     android_graphics_Bitmap
 * Method:    native_recycle
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Bitmap_native_1recycle
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
