/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_GskCanvas */

#ifndef _Included_android_graphics_GskCanvas
#define _Included_android_graphics_GskCanvas
#ifdef __cplusplus
extern "C" {
#endif
#undef android_graphics_GskCanvas_HAS_ALPHA_LAYER_SAVE_FLAG
#define android_graphics_GskCanvas_HAS_ALPHA_LAYER_SAVE_FLAG 4L
/*
 * Class:     android_graphics_GskCanvas
 * Method:    native_drawBitmap
 * Signature: (JJIIIII)V
 */
JNIEXPORT void JNICALL Java_android_graphics_GskCanvas_native_1drawBitmap
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     android_graphics_GskCanvas
 * Method:    native_drawRect
 * Signature: (JFFFFI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_GskCanvas_native_1drawRect
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     android_graphics_GskCanvas
 * Method:    native_drawPath
 * Signature: (JJII)V
 */
JNIEXPORT void JNICALL Java_android_graphics_GskCanvas_native_1drawPath
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     android_graphics_GskCanvas
 * Method:    native_translate
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_GskCanvas_native_1translate
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_GskCanvas
 * Method:    native_rotate
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_GskCanvas_native_1rotate
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     android_graphics_GskCanvas
 * Method:    native_save
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_GskCanvas_native_1save
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_graphics_GskCanvas
 * Method:    native_restore
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_GskCanvas_native_1restore
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_graphics_GskCanvas
 * Method:    native_drawLine
 * Signature: (JFFFFIF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_GskCanvas_native_1drawLine
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     android_graphics_GskCanvas
 * Method:    native_drawText
 * Signature: (JLjava/lang/String;FFIF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_GskCanvas_native_1drawText
  (JNIEnv *, jobject, jlong, jstring, jfloat, jfloat, jint, jfloat);

/*
 * Class:     android_graphics_GskCanvas
 * Method:    native_drawRoundRect
 * Signature: (JFFFFFFIFI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_GskCanvas_native_1drawRoundRect
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jint);

/*
 * Class:     android_graphics_GskCanvas
 * Method:    native_scale
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_GskCanvas_native_1scale
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
