/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_app_ATLKeyboardDialog */

#ifndef _Included_android_app_ATLKeyboardDialog
#define _Included_android_app_ATLKeyboardDialog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_app_ATLKeyboardDialog
 * Method:    nativeInit
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_android_app_ATLKeyboardDialog_nativeInit
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
