/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_os_Parcel */

#ifndef _Included_android_os_Parcel
#define _Included_android_os_Parcel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_os_Parcel
 * Method:    native_writeInt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_os_Parcel_native_1writeInt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_os_Parcel
 * Method:    native_writeString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_os_Parcel_native_1writeString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     android_os_Parcel
 * Method:    native_readInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_os_Parcel_native_1readInt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_os_Parcel
 * Method:    native_readString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_os_Parcel_native_1readString
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
