/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_Path */

#ifndef _Included_android_graphics_Path
#define _Included_android_graphics_Path
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_Path
 * Method:    init1
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Path_init1
  (JNIEnv *, jclass);

/*
 * Class:     android_graphics_Path
 * Method:    init2
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Path_init2
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    native_reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    native_rewind
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1rewind
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    native_set
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1set
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    native_getFillType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Path_native_1getFillType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    native_setFillType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1setFillType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_isEmpty
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Path_native_1isEmpty
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    native_isRect
 * Signature: (JLandroid/graphics/RectF;)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Path_native_1isRect
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     android_graphics_Path
 * Method:    native_computeBounds
 * Signature: (JLandroid/graphics/RectF;)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1computeBounds
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     android_graphics_Path
 * Method:    native_incReserve
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1incReserve
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_moveTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1moveTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_rMoveTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1rMoveTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_lineTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1lineTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_rLineTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1rLineTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_quadTo
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1quadTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_rQuadTo
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1rQuadTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_cubicTo
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1cubicTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_rCubicTo
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1rCubicTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_arcTo
 * Signature: (JLandroid/graphics/RectF;FFZ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1arcTo
  (JNIEnv *, jclass, jlong, jobject, jfloat, jfloat, jboolean);

/*
 * Class:     android_graphics_Path
 * Method:    native_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    native_addRect
 * Signature: (JLandroid/graphics/RectF;I)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addRect__JLandroid_graphics_RectF_2I
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_addRect
 * Signature: (JFFFFI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addRect__JFFFFI
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_addOval
 * Signature: (JLandroid/graphics/RectF;I)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addOval
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_addCircle
 * Signature: (JFFFI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addCircle
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_addArc
 * Signature: (JLandroid/graphics/RectF;FF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addArc
  (JNIEnv *, jclass, jlong, jobject, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_addRoundRect
 * Signature: (JFFFFFFI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addRoundRect__JFFFFFFI
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_addRoundRect
 * Signature: (JLandroid/graphics/RectF;[FI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addRoundRect__JLandroid_graphics_RectF_2_3FI
  (JNIEnv *, jclass, jlong, jobject, jfloatArray, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_addPath
 * Signature: (JJFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addPath__JJFF
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_addPath
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addPath__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    native_addPath
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addPath__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    native_offset
 * Signature: (JFFJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1offset__JFFJ
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    native_offset
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1offset__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_setLastPoint
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1setLastPoint
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_transform
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1transform__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    native_transform
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1transform__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    native_op
 * Signature: (JJIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Path_native_1op
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    finalizer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_finalizer
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
