/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_security_keystore_AndroidKeyStore */

#ifndef _Included_android_security_keystore_AndroidKeyStore
#define _Included_android_security_keystore_AndroidKeyStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_security_keystore_AndroidKeyStore
 * Method:    nativeSetKey
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_android_security_keystore_AndroidKeyStore_nativeSetKey
  (JNIEnv *, jclass, jstring, jstring, jbyteArray);

/*
 * Class:     android_security_keystore_AndroidKeyStore
 * Method:    nativeGetKey
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_android_security_keystore_AndroidKeyStore_nativeGetKey
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
